server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?userSSL=false
    username: root
    password: rootHost#123
    driver-class name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
